### ISSUE TITLE
Getting started 

### ISSUE THREAD

**Issue by ghost** [jetbasrawi/go.cqrs#1]
Hi, 

I've just pulled master and get the following issues.

`repository_test.go:17:2: cannot find package "github.com/jetbasrawi/go.geteventstore.testfeed`

Is there a file missing? 

In addition, I'm getting a complaint from the interface 

```
# github.com/jetbasrawi/go.cqrs/examples/simplecqrs/simplecqrs

examples/simplecqrs/simplecqrs/inventoryitem.go:33:29: not enough arguments in call to ycq.NewEventMessage

	have (string, *InventoryItemCreated)

	want (string, interface {}, *int)
```
Thanks

Paul

**Comment by jetbasrawi** [comment]
Hello I am out of office so answering on my phone. 

The test package is only needed if you want to run unit tests and is only referenced from the test files and should not error. What ide are you using?

I have never had any feedback on the other error or any errors actually. I hope you work it out. I am on the motorway all day so unable to help at the moment. 

Good luck

**Comment by LastManStanding** [comment]
Hi Jet, 
Thanks for getting back to me so quickly, I'm sure the issue is mine. Will push on and update you when I resolve it.

I'm running the whole package from the root in [Goland](https://www.jetbrains.com/go/). 

Drive carefully, all that snow and ice can't be great.
