### ISSUE TITLE
[Question] Why pass the reference to the memory address here?

### ISSUE THREAD

**Issue by tugberkugurlu** [jetbasrawi/go.cqrs#4]
> 👋 I am in the process of learning Go and this package is really useful resource to try to implement a solution with CQRS pattern. So, first of all, thanks for putting this out there 🙏 

This is more of a question than an issue. So, apologies in advance and it may be my lack of understanding on the language as well.

Here:

https://github.com/jetbasrawi/go.cqrs/blob/b0b8fdae71f38abdd791481e8255651520ac94e9/examples/simplecqrs/simplecqrs/inmem_repo.go#L14-L15

What is the specific reason to pass the memory address to the struct here (if I am understanding the usage of `*` and `&` correctly in this context) instead of actually pass it directly (i.e. make the return type `InMemoryRepo` instead of `*InMemoryRepo`)?

**Comment by jetbasrawi** [comment]
Hi tugberkugurlu, 

Thank you I am happy that it has been useful to you. Sorry for the long delay in replying. I clearly don't have notifications set up properly. :)

Thank you for challenging me to think about this. I was also learning Go and CQRS at the time I wrote this package. In this case the InMemoryRepo is not a large structure so returning a copy of it would probably not be an issue.

More recently I tend to prefer to pass around copies and use profiling to determine when to prefer passing by reference.
