### ISSUE TITLE
[Question]aggregate.OriginalVersion vs ExpectedVersion

### ISSUE THREAD

**Issue by samoilenko** [jetbasrawi/go.cqrs#6]
Hi, I'm curious in which cases the expected version doesn't equal aggregate.OriginalVersion().

https://github.com/jetbasrawi/go.cqrs/blob/e4d812d57f090ecede016aa36d70c73626a8eb17/examples/simplecqrs/simplecqrs/command_handlers.go#L69

https://github.com/jetbasrawi/go.cqrs/blob/e4d812d57f090ecede016aa36d70c73626a8eb17/examples/simplecqrs/simplecqrs/inventoryitem_repo.go#L94

https://github.com/jetbasrawi/go.cqrs/blob/e4d812d57f090ecede016aa36d70c73626a8eb17/repository.go#L165

https://github.com/jetbasrawi/go.geteventstore/blob/359416153188c8c42a27cd9a6e61e1c72ee6f3b8/streamwriter.go#L42

unfortunately, I can't imagine those cases.
Thanks in advance

**Comment by jetbasrawi** [comment]
Expected version is the last known state of the persisted stream. It is used to identify concurrency issues. Imagine you have a persisted stream that you have read at version n, and you create an event with version n+1 when you come to save, the stream should be at version n. If it is not then someone else has saved events and your n + 1 conflicts with the new stream version. 

You would then choose what to do in response to this. The OriginalVersion of the aggregate when loaded remains valid, but you may increment your expected version to take account of your awareness that the stream has been incremented by some other process. Hope this helps.

**Comment by samoilenko** [comment]
> Hope this helps.
Thanks, it helped.
